# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fixtures", "0010_auto_20170329_1253"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "import_type",
                    models.IntegerField(
                        choices=[
                            (0, "Match data"),
                            (1, "Batting Performance"),
                            (2, "Bowling Performance"),
                            (3, "Fielding Performance"),
                            (4, "Match Performance"),
                        ]
                    ),
                ),
                ("fname", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("imported_on", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixtures.Match"
                    ),
                ),
            ],
        ),
    ]
