# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="fname",
            field=models.FileField(upload_to="import_uploads/%Y/%m/%d/"),
        ),
    ]
