# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0004_auto_20170401_1231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimport",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
