# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0005_auto_20170401_1235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimport",
            name="description",
            field=models.CharField(default="--", max_length=100),
        ),
    ]
