# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0006_auto_20170401_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataimport",
            name="notes",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="dataimport",
            name="description",
            field=models.CharField(
                default="--", help_text="Auto set on save.", max_length=100
            ),
        ),
    ]
