# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_auto_20170329_1056"),
        ("imports", "0009_auto_20170401_2339"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataimport",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.MemberGroup",
            ),
        ),
    ]
