# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0010_dataimport_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataimport", old_name="group", new_name="member_group",
        ),
    ]
