# Generated by Django 2.0.2 on 2018-02-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0011_auto_20170401_2353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimport",
            name="member_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.MemberGroup",
            ),
        ),
    ]
