# Generated by Django 2.0.2 on 2018-03-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fixtures", "0025_auto_20180323_1157"),
    ]

    operations = [
        migrations.CreateModel(
            name="BallByBall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("over", models.IntegerField()),
                ("ball", models.IntegerField()),
                ("runs", models.IntegerField()),
                ("extras", models.IntegerField()),
                ("fours", models.BooleanField(default=False)),
                ("sixes", models.BooleanField(default=False)),
                ("dot_ball", models.BooleanField(default=False)),
                ("wicket_type", models.CharField(max_length=50, null=True)),
                ("ball_type", models.CharField(default="normal", max_length=100)),
                ("last_ball_of_over", models.BooleanField(default=False)),
                ("comments", models.CharField(max_length=10000, null=True)),
                (
                    "batsman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ball_by_ball_batsman",
                        to="fixtures.Player",
                    ),
                ),
                (
                    "batting_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batting_team",
                        to="fixtures.Team",
                    ),
                ),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ball_by_ball_bowler",
                        to="fixtures.Player",
                    ),
                ),
                (
                    "bowling_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bowling_team",
                        to="fixtures.Team",
                    ),
                ),
                (
                    "fielders",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ball_by_ball_fielder",
                        to="fixtures.Player",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixtures.Match"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(default="KEYS", max_length=200)),
                ("property_value", models.CharField(max_length=200)),
                (
                    "property_context",
                    models.CharField(default="CricketAPI", max_length=200),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Player",
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Squad",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        ),
    ]
