# Generated by Django 2.0.2 on 2018-04-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0032_auto_20180406_0855"),
        ("live_scores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballbyball",
            name="ball_key",
            field=models.CharField(default="abc", max_length=50),
        ),
        migrations.AddField(
            model_name="ballbyball",
            name="wicket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ball_by_ball_wicket",
                to="fixtures.Player",
            ),
        ),
    ]
