# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-02 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0029_auto_20180228_1643"),
        ("live_scores", "0001_initial"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='BallByBall',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('match', models.CharField(max_length=100)),
        #         ('over', models.IntegerField()),
        #         ('ball', models.IntegerField()),
        #         ('runs', models.IntegerField()),
        #         ('extras', models.IntegerField()),
        #         ('wicket', models.CharField(max_length=100)),
        #         ('comments', models.CharField(max_length=100)),
        #         ('batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ball_by_ball_batsman', to='fixtures.Player')),
        #         ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ball_by_ball_bowler', to='fixtures.Player')),
        #         ('fielders', models.ManyToManyField(to='fixtures.Player')),
        #     ],
        # ),
    ]
