# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_scores", "0002_ballbyball"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballbyball",
            name="comments",
            field=models.CharField(max_length=100, null=True),
        ),
        # migrations.AlterField(
        #   model_name='ballbyball',
        #  name='wicket',
        # field=models.CharField(max_length=100, null=True),
        # ),
    ]
