# Generated by Django 3.0.3 on 2020-02-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("live_scores", "0004_auto_20180302_1412"),
        ("live_scores", "0003_ballbyball_innings"),
    ]

    operations = []
