# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0003_auto_20170325_1147"),
        (
            "members",
            "0002_groupplayerscoringmethod_grouppredictionscoringmethod_groupsubmissionvalidationrule",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPostMatchPredictionScoringMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.MemberGroup",
                    ),
                ),
                (
                    "parent_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rules.PostMatchPredictionScoringMethod",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="groupplayerscoringmethod", name="rule",),
        migrations.RemoveField(model_name="grouppredictionscoringmethod", name="rule",),
        migrations.RemoveField(
            model_name="groupsubmissionvalidationrule", name="rule",
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="parent_rule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="rules.PlayerScoringMethod",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="parent_rule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="rules.PredictionScoringMethod",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupsubmissionvalidationrule",
            name="parent_rule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="rules.PredictionSubmissionValidationRule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="members.MemberGroup"
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="members.MemberGroup"
            ),
        ),
        migrations.AlterField(
            model_name="groupsubmissionvalidationrule",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="members.MemberGroup"
            ),
        ),
    ]
