# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_auto_20170325_1236"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membergrouprules",
            options={"verbose_name_plural": "Member group rules"},
        ),
    ]
