# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_auto_20170325_1242"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membergrouprules",
            old_name="player_scoring_rules",
            new_name="group_player_scoring_rules",
        ),
        migrations.RenameField(
            model_name="membergrouprules",
            old_name="post_match_prediction_scoring_rules",
            new_name="group_post_match_prediction_scoring_rules",
        ),
        migrations.RenameField(
            model_name="membergrouprules",
            old_name="prediction_scoring_rules",
            new_name="group_prediction_scoring_rules",
        ),
        migrations.RenameField(
            model_name="membergrouprules",
            old_name="prediction_validation_rules",
            new_name="group_prediction_validation_rules",
        ),
    ]
