# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_auto_20170325_1250"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membergrouprules", old_name="group", new_name="member_group",
        ),
    ]
