# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_membergrouprules_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupplayerscoringmethod", name="parent_rule",
        ),
        migrations.RemoveField(
            model_name="grouppostmatchpredictionscoringmethod", name="parent_rule",
        ),
        migrations.RemoveField(
            model_name="grouppredictionscoringmethod", name="parent_rule",
        ),
        migrations.RemoveField(
            model_name="groupsubmissionvalidationrule", name="parent_rule",
        ),
        migrations.RemoveField(
            model_name="membergrouprules", name="group_player_scoring_rules",
        ),
        migrations.RemoveField(
            model_name="membergrouprules",
            name="group_post_match_prediction_scoring_rules",
        ),
        migrations.RemoveField(
            model_name="membergrouprules", name="group_prediction_scoring_rules",
        ),
        migrations.RemoveField(
            model_name="membergrouprules", name="group_prediction_validation_rules",
        ),
        migrations.RemoveField(model_name="membergrouprules", name="member_group",),
        migrations.DeleteModel(name="GroupPlayerScoringMethod",),
        migrations.DeleteModel(name="GroupPostMatchPredictionScoringMethod",),
        migrations.DeleteModel(name="GroupPredictionScoringMethod",),
        migrations.DeleteModel(name="GroupSubmissionValidationRule",),
        migrations.DeleteModel(name="MemberGroupRules",),
    ]
