# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "rules",
            "0004_groupplayerscoringmethod_groupplayerscoringresult_grouppostmatchpredictionscoringmethod_grouppostmat",
        ),
        ("members", "0010_auto_20170325_1431"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberGroupRules",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "group_player_scoring_rules",
                    models.ManyToManyField(
                        blank=True, to="rules.GroupPlayerScoringMethod"
                    ),
                ),
                (
                    "group_post_match_prediction_scoring_rules",
                    models.ManyToManyField(
                        blank=True, to="rules.GroupPostMatchPredictionScoringMethod"
                    ),
                ),
                (
                    "group_prediction_scoring_rules",
                    models.ManyToManyField(
                        blank=True, to="rules.GroupPredictionScoringMethod"
                    ),
                ),
                (
                    "group_prediction_validation_rules",
                    models.ManyToManyField(
                        blank=True, to="rules.GroupPredictionSubmissionValidationRule"
                    ),
                ),
                (
                    "member_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.MemberGroup",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Member group rules",},
        ),
    ]
