# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0007_auto_20170329_0029"),
        ("members", "0011_membergrouprules"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupLeaderBoard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaderBoardEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_points",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("this_match", models.FloatField(default=0.0)),
                ("total", models.IntegerField(default=0.0)),
                ("previous_position", models.IntegerField(default=0)),
                ("position_now", models.IntegerField(default=0)),
                ("movement", models.IntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Member"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupleaderboard",
            name="entries",
            field=models.ManyToManyField(to="members.LeaderBoardEntry"),
        ),
        migrations.AddField(
            model_name="groupleaderboard",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Match"
            ),
        ),
        migrations.AddField(
            model_name="groupleaderboard",
            name="member_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.MemberGroup"
            ),
        ),
    ]
