# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_auto_20170329_0029"),
    ]

    operations = [
        migrations.RemoveField(model_name="groupleaderboard", name="entries",),
        migrations.AddField(
            model_name="leaderboardentry",
            name="leader_board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.GroupLeaderBoard",
            ),
            preserve_default=False,
        ),
    ]
