# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_auto_20170329_0231"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupleaderboard",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
