# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_groupleaderboard_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupleaderboard",
            name="number",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
