# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_auto_20170329_0311"),
    ]

    operations = [
        migrations.RemoveField(model_name="groupleaderboard", name="number",),
        migrations.AddField(
            model_name="groupleaderboard",
            name="board_number",
            field=models.FloatField(default=0.0),
        ),
    ]
