# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0020_auto_20170329_0507"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboardentry",
            options={
                "ordering": ["-total"],
                "verbose_name_plural": "Leader Board Entries",
            },
        ),
    ]
