# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0023_auto_20170409_1058"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Member"
                    ),
                ),
                (
                    "member_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.MemberGroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membergroup",
            name="members",
            field=models.ManyToManyField(
                through="members.Membership", to="members.Member"
            ),
        ),
    ]
