# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0020_auto_20170506_0610"),
        ("members", "0024_auto_20170414_0330"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergrouprules",
            name="group_leaderboard_scoring_rules",
            field=models.ManyToManyField(
                blank=True, to="rules.GroupLeaderBoardScoringMethod"
            ),
        ),
    ]
