# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0021_auto_20170531_1251"),
        ("members", "0025_membergrouprules_group_leaderboard_scoring_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergrouprules",
            name="group_tournament_scoring_rules",
            field=models.ManyToManyField(
                blank=True, to="rules.GroupTournamentScoringMethod"
            ),
        ),
    ]
