# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0026_membergrouprules_group_tournament_scoring_rules"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membergrouprules",
            old_name="group_prediction_validation_rules",
            new_name="group_submission_validation_rules",
        ),
    ]
