# Generated by Django 2.0.2 on 2018-02-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0027_auto_20180209_0517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupleaderboard",
            name="member_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="members.MemberGroup"
            ),
        ),
        migrations.AlterField(
            model_name="membergrouprules",
            name="member_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="members.MemberGroup"
            ),
        ),
    ]
