# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-10 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0024_auto_20170605_1127"),
        ("members", "0027_auto_20180209_0517"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergroup",
            name="tournaments",
            field=models.ManyToManyField(to="fixtures.Tournament"),
        ),
    ]
