# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-03 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0028_membergroup_tournaments"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
