# Generated by Django 2.0.2 on 2018-03-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0029_membership_is_admin"),
        ("members", "0028_auto_20180209_1009"),
    ]

    operations = []
