# Generated by Django 2.0.2 on 2018-03-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0030_merge_20180310_0329"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberGroupInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invited_name", models.CharField(max_length=50)),
                ("invited_email", models.EmailField(max_length=254)),
                ("invited_on", models.DateTimeField(auto_now_add=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_time", models.DateTimeField(blank=True, null=True)),
                ("accepted", models.BooleanField(default=False)),
                ("invitation_code", models.CharField(max_length=10)),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Member"
                    ),
                ),
                (
                    "member_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.MemberGroup",
                    ),
                ),
            ],
        ),
    ]
