# Generated by Django 2.0.2 on 2018-03-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0031_membergroupinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergrouprules",
            name="member_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.MemberGroup"
            ),
        ),
    ]
