# Generated by Django 2.0.2 on 2018-03-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0033_auto_20180312_0424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergroupinvitation",
            name="accepting_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="members.Member",
            ),
        ),
        migrations.AlterField(
            model_name="membergroupinvitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="members.Member",
            ),
        ),
    ]
