# Generated by Django 2.0.2 on 2018-03-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0034_auto_20180312_0439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergroupinvitation",
            name="member_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.MemberGroup"
            ),
        ),
    ]
