# Generated by Django 2.0.2 on 2018-04-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0035_auto_20180315_2243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergroup",
            name="tournaments",
            field=models.ManyToManyField(
                related_name="participating_member_groups", to="fixtures.Tournament"
            ),
        ),
    ]
