# Generated by Django 2.0.2 on 2018-04-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0036_auto_20180403_0549"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership", unique_together={("member", "member_group")},
        ),
    ]
