# Generated by Django 2.0.2 on 2018-08-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0037_auto_20180408_0327"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="tournament_score",
            field=models.FloatField(default=0.0),
        ),
    ]
