# Generated by Django 2.0.2 on 2018-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0041_leaderboardentry_tournament_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardentry",
            name="tournament_score",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
