# Generated by Django 2.0.2 on 2018-08-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0042_auto_20180803_0529"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaderboardentry", name="tournament_score",),
    ]
