# Generated by Django 2.0.2 on 2018-08-04 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0044_leaderboardentry_tournament_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaderboardentry",
            old_name="tournament_score",
            new_name="tournament_predictions_score",
        ),
    ]
