# Generated by Django 2.0.2 on 2018-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0047_leaderboardentry_tournament_predictions_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupleaderboard",
            name="show_ts_column",
            field=models.BooleanField(default=False),
        ),
    ]
