# Generated by Django 2.0.2 on 2019-07-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0049_auto_20190526_0402"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupleaderboard",
            old_name="show_ts_column",
            new_name="is_tournament_leaderboard",
        ),
    ]
