# Generated by Django 2.0.2 on 2019-07-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0050_auto_20190718_0805"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
