# Generated by Django 2.0.2 on 2019-09-27 01:48

from django.db import migrations, models

import members.models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0051_membership_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergroup",
            name="invitation_code",
            field=models.CharField(
                default=members.models.generate_invite_code, max_length=10
            ),
        ),
    ]
