# Generated by Django 2.0.2 on 2019-11-26 13:18

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0053_auto_20190927_0154"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberVerification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[members.models.mobile_validator],
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "mobile_verification_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_mobile_verified", models.BooleanField(default=False)),
                ("email_confirmation_ts", models.DateTimeField(null=True)),
                ("mobile_confirmation_ts", models.DateTimeField(null=True)),
                ("verification_email_sent", models.BooleanField(default=False)),
                ("verification_sms_sent", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="mobile_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memberverification",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.Member"
            ),
        ),
    ]
