# Generated by Django 2.0.2 on 2020-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_auto_20191126_1848"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="marked_inactive",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
