# Generated by Django 2.0.2 on 2020-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0055_auto_20200205_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
