# Generated by Django 3.0.3 on 2020-03-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0056_auto_20200207_1233"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergroup",
            name="reserved",
            field=models.BooleanField(default=False),
        ),
    ]
