# Generated by Django 3.0.3 on 2020-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0055_membership_marked_inactive"),
        ("members", "0057_membergroup_reserved"),
    ]

    operations = []
