# Generated by Django 3.0.3 on 2020-04-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0058_merge_20200409_2334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="marked_inactive",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
