# Generated by Django 3.0.3 on 2020-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0059_auto_20200410_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Male"),
                    (2, "Female"),
                    (3, "Others"),
                    (4, "Prefer Not To Say"),
                ],
                null=True,
            ),
        ),
    ]
