# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="playerscores", name="total_scores",),
        migrations.AddField(
            model_name="playerscores",
            name="total_score",
            field=models.FloatField(default=0),
        ),
    ]
