# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_auto_20170321_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerscores",
            name="detailed_scoring",
            field=models.ManyToManyField(
                related_name="match_player_scoring_results",
                to="rules.PlayerScoringResult",
            ),
        ),
    ]
