# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0004_playertournamenthistory_team"),
        ("stats", "0003_auto_20170325_0048"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="battingperformance", unique_together=set([("player", "match")]),
        ),
        migrations.AlterUniqueTogether(
            name="bowlingperformance", unique_together=set([("player", "match")]),
        ),
        migrations.AlterUniqueTogether(
            name="fieldingperformance", unique_together=set([("player", "match")]),
        ),
        migrations.AlterUniqueTogether(
            name="matchperformance", unique_together=set([("player", "match")]),
        ),
        migrations.AlterUniqueTogether(
            name="playerscores", unique_together=set([("player", "match")]),
        ),
    ]
