# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0010_auto_20170329_1253"),
        ("stats", "0005_battingperformance_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="bowlingperformance",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="fieldingperformance",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="matchperformance",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="playerscores",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Team",
            ),
        ),
    ]
