# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_auto_20170330_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battingperformance",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
            ),
        ),
        migrations.AlterField(
            model_name="bowlingperformance",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
            ),
        ),
        migrations.AlterField(
            model_name="fieldingperformance",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
            ),
        ),
        migrations.AlterField(
            model_name="matchperformance",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
            ),
        ),
        migrations.AlterField(
            model_name="playerscores",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
            ),
        ),
    ]
