# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0010_auto_20170329_1253"),
        ("stats", "0007_auto_20170330_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="battingperformance",
            name="fall_of_wicket_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battingperformance",
            name="not_out_batsman",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="not_out_batsman",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="battingperformance",
            name="not_out_batsman_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battingperformance",
            name="wicket_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchperformance",
            name="most_runs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matchperformance",
            name="most_wickets",
            field=models.BooleanField(default=False),
        ),
    ]
