# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_auto_20170330_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battingperformance",
            name="dismissal",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Bowled"),
                    (2, "Caught"),
                    (3, "Not Out"),
                    (4, "Retired Hurt"),
                    (5, "Timed Out"),
                    (6, "Handled"),
                    (7, "Hit Twice"),
                    (8, "Hit Wicket"),
                    (9, "LBW"),
                    (10, "Obstructing Field"),
                    (11, "Stumped"),
                    (12, "Run Out"),
                    (13, "Absent Hurt"),
                ],
                null=True,
            ),
        ),
    ]
