# Generated by Django 2.0.2 on 2018-02-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0009_auto_20170609_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerscores",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Match"
            ),
        ),
        migrations.AlterField(
            model_name="playerscores",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Player"
            ),
        ),
    ]
