# Generated by Django 2.0.2 on 2018-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0010_auto_20180209_1009"),
    ]

    operations = [
        migrations.AddField(
            model_name="bowlingperformance",
            name="is_maiden",
            field=models.BooleanField(default=False),
        ),
    ]
