# Generated by Django 2.0.2 on 2018-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0011_bowlingperformance_is_maiden"),
    ]

    operations = [
        migrations.AddField(
            model_name="bowlingperformance",
            name="hattrick_count",
            field=models.IntegerField(default=0),
        ),
    ]
