# Generated by Django 2.0.2 on 2018-04-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0012_bowlingperformance_hattrick_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battingperformance",
            name="was_out",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Out"),
                    (2, "Not Out"),
                    (3, "Did Not Bat"),
                ],
                default=0,
            ),
        ),
    ]
