# Generated by Django 2.0.2 on 2019-06-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0040_auto_20190520_1141"),
        ("stats", "0013_auto_20180408_0842"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_name", models.CharField(max_length=100)),
                ("stat_value", models.FloatField(default=0.0)),
                ("stat_unit", models.IntegerField(blank=True, null=True)),
                ("computed_on", models.DateTimeField(auto_now_add=True)),
                ("is_latest", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        ),
    ]
