# Generated by Django 2.0.2 on 2019-06-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0040_auto_20190520_1141"),
        ("stats", "0014_playerstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_name", models.CharField(max_length=100)),
                ("stat_value", models.FloatField(default=0.0)),
                ("stat_unit", models.IntegerField(blank=True, null=True)),
                ("stat_index", models.IntegerField(null=True)),
                ("computed_on", models.DateTimeField(auto_now_add=True)),
                ("is_latest", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="playerstats", name="match",),
        migrations.RemoveField(model_name="playerstats", name="player",),
        migrations.RemoveField(model_name="playerstats", name="team",),
        migrations.RemoveField(model_name="playerstats", name="tournament",),
        migrations.DeleteModel(name="PlayerStats",),
    ]
