# Generated by Django 2.0.2 on 2019-08-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0015_auto_20190617_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="battingperformance",
            name="innings",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bowlingperformance",
            name="innings",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fieldingperformance",
            name="innings",
            field=models.IntegerField(default=1),
        ),
    ]
