# Generated by Django 2.0.2 on 2019-08-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0045_auto_20190801_0549"),
        ("stats", "0016_auto_20190807_1231"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="battingperformance", unique_together={("player", "match", "innings")},
        ),
        migrations.AlterUniqueTogether(
            name="bowlingperformance", unique_together={("player", "match", "innings")},
        ),
        migrations.AlterUniqueTogether(
            name="fieldingperformance",
            unique_together={("player", "match", "innings")},
        ),
    ]
