# Generated by Django 2.0.2 on 2020-02-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_auto_20191126_1848"),
        ("stats", "0017_auto_20190807_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstat",
            name="member_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.MemberGroup",
            ),
        ),
    ]
