# Generated by Django 2.0.2 on 2020-02-12 08:03

from django.db import migrations
import python_field.python_field


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0018_playerstat_member_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstat",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=200, null=True
            ),
        ),
    ]
