# Generated by Django 3.0.3 on 2020-02-26 06:15

from django.db import migrations, models
import django.db.models.deletion
import python_field.python_field


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_auto_20191126_1848"),
        ("fixtures", "0063_auto_20200222_0629"),
        ("stats", "0020_teamstat"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldStat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_name", models.CharField(max_length=100)),
                ("stat_value", models.FloatField(default=0.0)),
                ("stat_unit", models.IntegerField(blank=True, null=True)),
                ("stat_index", models.IntegerField(null=True)),
                (
                    "match_or_tournament_format",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")],
                        null=True,
                    ),
                ),
                (
                    "calculation",
                    python_field.python_field.PythonCodeField(
                        blank=True, max_length=200, null=True
                    ),
                ),
                ("computed_on", models.DateTimeField(auto_now_add=True)),
                ("is_latest", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Match",
                    ),
                ),
                (
                    "member_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.MemberGroup",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        ),
    ]
