# Generated by Django 3.0.3 on 2020-02-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_auto_20191126_1848"),
        ("fixtures", "0063_auto_20200222_0629"),
        ("stats", "0021_fieldstat"),
    ]

    operations = [
        migrations.RenameModel(old_name="FieldStat", new_name="PredictionFieldStat",),
    ]
