# Generated by Django 3.0.3 on 2020-02-27 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0063_auto_20200222_0629"),
        ("stats", "0022_auto_20200226_0619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionfieldstat",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Team",
            ),
        ),
    ]
