# Generated by Django 3.0.3 on 2020-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0023_auto_20200227_0507"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstat",
            name="add_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstat",
            name="removed_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="predictionfieldstat",
            name="add_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="predictionfieldstat",
            name="removed_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstat",
            name="add_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstat",
            name="removed_counter",
            field=models.IntegerField(default=0),
        ),
    ]
