# Generated by Django 3.0.3 on 2020-03-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0024_auto_20200302_0542"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstat",
            name="match_or_tournament_format",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teamstat",
            name="match_or_tournament_format",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")],
                null=True,
            ),
        ),
    ]
