# Generated by Django 3.0.3 on 2020-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0025_auto_20200328_0450"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionfieldstat",
            name="raw_stats_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
