# Generated by Django 3.0.3 on 2020-04-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0026_predictionfieldstat_raw_stats_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictionfieldstat",
            old_name="raw_stats_value",
            new_name="raw_stat_value",
        ),
    ]
