# Generated by Django 3.0.3 on 2020-04-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0027_auto_20200405_0321"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictionfieldstat",
            old_name="raw_stat_value",
            new_name="raw_input_value",
        ),
    ]
