# Generated by Django 3.0.3 on 2020-09-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0028_auto_20200405_0329"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstat",
            name="submission_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="predictionfieldstat",
            name="submission_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamstat",
            name="submission_count",
            field=models.IntegerField(default=0),
        ),
    ]
