# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="toss_outcome",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Heads"), (2, "Tails"), (3, "Unknown")],
                default=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Club",
            ),
        ),
    ]
