# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0003_auto_20170319_1412"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamenthistory",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fixtures.Team",
            ),
            preserve_default=False,
        ),
    ]
