# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0015_auto_20170328_1232"),
        ("fixtures", "0004_playertournamenthistory_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentDefaultRules",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
                (
                    "tournament_player_scoring_method",
                    models.ManyToManyField(
                        blank=True, null=True, to="rules.PlayerScoringMethod"
                    ),
                ),
                (
                    "tournament_post_predictions_scoring_methods",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="rules.PostMatchPredictionScoringMethod",
                    ),
                ),
                (
                    "tournament_prediction_scoring_method",
                    models.ManyToManyField(
                        blank=True, null=True, to="rules.PredictionScoringMethod"
                    ),
                ),
                (
                    "tournament_prediction_validation_rules",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="rules.PredictionSubmissionValidationRule",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="playertournamenthistory",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Player"
            ),
        ),
        migrations.AlterField(
            model_name="playertournamenthistory",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Team"
            ),
        ),
        migrations.AlterField(
            model_name="playertournamenthistory",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Tournament"
            ),
        ),
    ]
