# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0005_auto_20170328_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentdefaultrules",
            name="tournament_player_scoring_method",
            field=models.ManyToManyField(blank=True, to="rules.PlayerScoringMethod"),
        ),
        migrations.AlterField(
            model_name="tournamentdefaultrules",
            name="tournament_post_predictions_scoring_methods",
            field=models.ManyToManyField(
                blank=True, to="rules.PostMatchPredictionScoringMethod"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentdefaultrules",
            name="tournament_prediction_scoring_method",
            field=models.ManyToManyField(
                blank=True, to="rules.PredictionScoringMethod"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentdefaultrules",
            name="tournament_prediction_validation_rules",
            field=models.ManyToManyField(
                blank=True, to="rules.PredictionSubmissionValidationRule"
            ),
        ),
    ]
