# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0007_auto_20170329_0029"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamenthistory",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="date_withdrawn",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="withdrawn",
            field=models.BooleanField(default=False),
        ),
    ]
