# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0008_auto_20170329_1137"),
    ]

    operations = [
        migrations.RemoveField(model_name="playertournamenthistory", name="active",),
        migrations.RemoveField(model_name="playertournamenthistory", name="withdrawn",),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Withdrawn")], default=1
            ),
        ),
    ]
