# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0009_auto_20170329_1209"),
    ]

    operations = [
        migrations.RemoveField(model_name="squad", name="captain",),
        migrations.RemoveField(model_name="squad", name="wicket_keeper",),
    ]
