# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0010_auto_20170329_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_result",
            field=models.IntegerField(
                choices=[
                    (-1, "Unknown"),
                    (0, "Win"),
                    (1, "Tie"),
                    (2, "Draw"),
                    (3, "No Result"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_outcome",
            field=models.IntegerField(choices=[(2, "Completed"), (3, "Scheduled")]),
        ),
        migrations.AlterField(
            model_name="match",
            name="second_innings_balls",
            field=models.IntegerField(default=6),
        ),
    ]
