# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0011_auto_20170402_0408"),
    ]

    operations = [
        migrations.RemoveField(model_name="match", name="match_outcome",),
        migrations.AddField(
            model_name="match",
            name="match_status",
            field=models.IntegerField(
                choices=[(2, "Completed"), (3, "Scheduled"), (1, "Live")], default=2
            ),
            preserve_default=False,
        ),
    ]
