# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0012_auto_20170402_0624"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="host_country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_level",
            field=models.IntegerField(
                choices=[(1, "International"), (0, "Domestic")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")]
            ),
        ),
    ]
