# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0013_auto_20170402_0724"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="first_innings_bowled",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="first_innings_free_hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="first_innings_lbw",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="second_innings_bowled",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="second_innings_free_hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="second_innings_lbw",
            field=models.IntegerField(default=0),
        ),
    ]
