# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0014_auto_20170404_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="most_runs_by",
            field=models.ManyToManyField(
                blank=True, related_name="_match_most_runs_by_+", to="fixtures.Player"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="most_wickets_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="_match_most_wickets_by_+",
                to="fixtures.Player",
            ),
        ),
    ]
