# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0016_auto_20170404_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squad",
            name="matches_played",
            field=models.CharField(default="Not Played", max_length=100),
        ),
    ]
