# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0017_auto_20170408_0131"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="submissions_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
