# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0019_auto_20170426_1156"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="super_over_played",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="super_over_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="fixtures.Squad",
            ),
        ),
    ]
