# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0020_auto_20170430_0603"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="first_wicket_gone_in_over",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="win_margin_runs",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
