# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0021_auto_20170531_1251"),
        ("fixtures", "0021_auto_20170525_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentdefaultrules",
            name="tournament_leaderboard_scoring_methods",
            field=models.ManyToManyField(
                blank=True, to="rules.LeaderBoardScoringMethod"
            ),
        ),
    ]
