# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fixtures",
            "0022_tournamentdefaultrules_tournament_leaderboard_scoring_methods",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="dl_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="dl_calculated_cinning_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="dl_overs",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="dl_target",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
