# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0023_auto_20170605_1124"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="dl_calculated_cinning_score",
            new_name="dl_calculated_winning_score",
        ),
        migrations.AddField(
            model_name="match",
            name="dl_overs_balls",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
