# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0024_auto_20170605_1127"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSquadInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=64)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayingSquad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playing_squad_number", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixtures.Match"
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        through="fixtures.PlayerSquadInfo",
                        to="fixtures.Player",
                    ),
                ),
            ],
        ),
        # migrations.AddField(
        #     model_name='squad',
        #     name='tournament',
        #     field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='fixtures.Tournament'),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name="playingsquad",
            name="team_tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.Squad"
            ),
        ),
        migrations.AddField(
            model_name="playersquadinfo",
            name="playingSquad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fixtures.PlayingSquad"
            ),
        ),
    ]
