# Generated by Django 2.0.2 on 2018-03-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0024_auto_20170605_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamenthistory",
            name="player_skill",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "All Rounder"),
                    (1, "Batsman"),
                    (2, "Bowler"),
                    (3, "Keeper"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="squad",
            name="tournament",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Tournament",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="match",
            name="team_one",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_team_one",
                to="fixtures.Squad",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_team_two",
                to="fixtures.Squad",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="venue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Venue",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Country",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=models.DateTimeField(null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="host_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Country",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateTimeField(null=True, verbose_name="Start Date"),
        ),
        migrations.AlterUniqueTogether(
            name="match", unique_together={("tournament", "name")},
        ),
    ]
