# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-18 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0025_auto_20180216_2346"),
    ]

    operations = [
        migrations.RemoveField(model_name="playersquadinfo", name="role",),
        migrations.AddField(
            model_name="playersquadinfo",
            name="player_role",
            field=models.IntegerField(
                blank=True, choices=[(1, "Captain"), (2, "Keeper")], null=True
            ),
        ),
        migrations.AddField(
            model_name="playersquadinfo",
            name="player_skill",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "All Rounder"),
                    (1, "Batsman"),
                    (2, "Bowler"),
                    (2, "Keeper"),
                ],
                null=True,
            ),
        ),
    ]
