# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0026_auto_20180218_0552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=models.DateTimeField(null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="host_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Country",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateTimeField(null=True, verbose_name="Start Date"),
        ),
    ]
