# Generated by Django 2.0.2 on 2018-03-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0026_tournament_submissions_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Venue",
            ),
        ),
    ]
