# Generated by Django 2.0.2 on 2018-03-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0027_auto_20180327_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Country",
            ),
        ),
    ]
