# Generated by Django 2.0.2 on 2018-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0028_auto_20180329_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="reference_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
