# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0028_auto_20180228_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Country",
            ),
        ),
    ]
