# Generated by Django 2.0.2 on 2018-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0030_auto_20180403_1228"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="post_toss_changes_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
