# Generated by Django 2.0.2 on 2018-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0031_match_post_toss_changes_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="toss_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
