# Generated by Django 2.0.2 on 2018-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0032_auto_20180406_0855"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
