# Generated by Django 2.0.2 on 2018-04-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0033_tournament_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="short_display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="abbreviation",
            field=models.CharField(default="", max_length=10),
        ),
    ]
