# Generated by Django 2.0.2 on 2018-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0034_auto_20180411_1159"),
    ]

    operations = [
        migrations.RemoveField(model_name="tournament", name="abbreviation",),
        migrations.AddField(
            model_name="team",
            name="abbreviation",
            field=models.CharField(default="", max_length=10),
        ),
    ]
