# Generated by Django 2.0.2 on 2018-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0035_auto_20180411_1206"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="player_skill",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "All Rounder"),
                    (1, "Batsman"),
                    (2, "Bowler"),
                    (3, "Keeper"),
                ],
                null=True,
            ),
        ),
    ]
