# Generated by Django 2.0.3 on 2019-05-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0036_player_player_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamenthistory",
            name="is_captain",
            field=models.BooleanField(default=False),
        ),
    ]
