# Generated by Django 2.0.2 on 2019-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0037_playertournamenthistory_is_captain"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="player_hand",
            field=models.IntegerField(
                choices=[(4, "Left Handed"), (5, "Right Handed")], default=5
            ),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="is_vice_captain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="jersey_number",
            field=models.IntegerField(default=0),
        ),
    ]
