# Generated by Django 2.0.2 on 2019-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0038_auto_20190520_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playertournamenthistory",
            name="player_skill",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "All-rounder"),
                    (1, "Batsman"),
                    (2, "Bowler"),
                    (3, "Wicket-keeper"),
                ],
                null=True,
            ),
        ),
    ]
