# Generated by Django 2.0.2 on 2019-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0039_auto_20190520_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_skill",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "All-rounder"),
                    (1, "Batsman"),
                    (2, "Bowler"),
                    (3, "Wicket-keeper"),
                ],
                null=True,
            ),
        ),
    ]
