# Generated by Django 2.0.3 on 2019-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0040_auto_20190520_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_result",
            field=models.IntegerField(
                choices=[
                    (-1, "Unknown"),
                    (0, "Win"),
                    (1, "Tie"),
                    (2, "Draw"),
                    (3, "No Result"),
                    (4, "Abandoned"),
                ],
                default=-1,
            ),
        ),
    ]
