# Generated by Django 2.0.2 on 2019-07-18 07:47

from django.db import migrations, models


def set_historical_fake_matches(apps, schema_editor):
    Match = apps.get_model("fixtures.Match")

    # IPL 2018, CWC 2019
    for mid in [185, 136]:
        try:
            m = Match.objects.get(id=mid)
            m.fake_match = True
            m.save()
        except Match.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0041_auto_20190703_0857"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="fake_match",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_historical_fake_matches),
    ]
