# Generated by Django 2.0.2 on 2019-07-20 05:25

from django.db import migrations, models

import timezone_field.fields

import pytz

from timezone_field.fields import TimeZoneField


def populate_timezones(apps, schema_editor):
    Timezone = apps.get_model("fixtures.Timezone")

    for zone in pytz.all_timezones:
        t = Timezone()
        t.tz = zone
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0042_match_fake_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tz", timezone_field.fields.TimeZoneField()),
            ],
        ),
        migrations.AddField(
            model_name="country",
            name="timezones",
            field=models.ManyToManyField(to="fixtures.Timezone"),
        ),
        migrations.RunPython(populate_timezones),
    ]
