# Generated by Django 2.0.3 on 2019-08-01 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0043_auto_20190720_0525"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="timezone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Timezone",
            ),
        ),
    ]
