# Generated by Django 2.0.3 on 2019-08-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0044_venue_timezone"),
    ]

    operations = [
        migrations.RemoveField(model_name="venue", name="timezone",),
        migrations.AddField(
            model_name="city",
            name="timezone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Timezone",
            ),
        ),
    ]
