# Generated by Django 2.0.2 on 2019-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0046_auto_20190813_1007"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="fourth_innings_balls",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="fourth_innings_overs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="fourth_innings_runs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="fourth_innings_wickets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="third_innings_balls",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="third_innings_overs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="third_innings_runs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="third_innings_wickets",
            field=models.IntegerField(default=0),
        ),
    ]
