# Generated by Django 2.0.2 on 2019-09-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0048_auto_20190819_0903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_team_one",
                to="fixtures.Squad",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_team_two",
                to="fixtures.Squad",
            ),
        ),
    ]
