# Generated by Django 2.0.2 on 2019-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0049_auto_20190911_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="bi_lateral",
            field=models.BooleanField(default=False),
        ),
    ]
