# Generated by Django 2.0.2 on 2019-09-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0050_tournament_bi_lateral"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="not_a_real_team",
            field=models.BooleanField(default=False),
        ),
    ]
