# Generated by Django 2.0.2 on 2019-09-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0051_team_not_a_real_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team", old_name="not_a_real_team", new_name="fake_team",
        ),
    ]
