# Generated by Django 2.0.3 on 2019-11-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0052_auto_20190921_0121"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamenthistory",
            name="odi_player",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="t20_player",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="test_player",
            field=models.BooleanField(default=False),
        ),
    ]
