# Generated by Django 2.0.2 on 2019-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0052_auto_20190921_0121"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="abbreviation",
            field=models.CharField(default="", max_length=10),
        ),
    ]
