# Generated by Django 2.0.3 on 2019-12-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0053_auto_20191130_0716"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamenthistory",
            name="odi_captain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="t20_captain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="test_captain",
            field=models.BooleanField(default=False),
        ),
    ]
