# Generated by Django 2.0.3 on 2019-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0054_auto_20191201_0930"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamenthistory",
            name="odi_vice_captain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="t20_vice_captain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playertournamenthistory",
            name="test_vice_captain",
            field=models.BooleanField(default=False),
        ),
    ]
