# Generated by Django 2.0.3 on 2019-12-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0055_auto_20191201_0936"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="abbreviation",
            field=models.CharField(default="", max_length=20),
        ),
    ]
