# Generated by Django 2.0.2 on 2019-12-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0057_auto_20191209_0803"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="odi_series",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="t20_series",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="test_series",
            field=models.BooleanField(default=False),
        ),
    ]
