# Generated by Django 2.0.2 on 2019-12-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0054_auto_20191211_1612"),
        ("fixtures", "0058_auto_20191225_0402"),
    ]

    operations = []
