# Generated by Django 2.0.2 on 2020-01-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0059_merge_20191227_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="team_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournament_team_one",
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="team_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournament_team_two",
                to="fixtures.Team",
            ),
        ),
    ]
