# Generated by Django 2.0.2 on 2020-01-23 08:54

from django.db import migrations
import python_field.python_field
import python_field.utils


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0060_auto_20200103_0414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="short_display_name_strategy",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: '{}, {}: {} vs. {}'.format(match.tournament.abbreviation, match.reference_name, match.team_one.team.abbreviation, match.team_two.team.abbreviation)",
                max_length=200,
                validators=[python_field.utils.is_code_and_lambda],
            ),
        ),
    ]
