# Generated by Django 3.0.3 on 2020-03-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0060_auto_20200103_0414"),
        ("fixtures", "0029_auto_20180228_1643"),
    ]

    operations = []
