# Generated by Django 3.0.3 on 2020-02-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0061_auto_20200123_0854"),
        ("fixtures", "0029_auto_20180228_1643"),
    ]

    operations = []
