# Generated by Django 3.0.3 on 2020-03-04 10:20

from django.db import migrations, models
import python_field.python_field
import python_field.utils


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0061_merge_20200304_1549"),
    ]
