# Generated by Django 3.0.3 on 2020-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0062_merge_20200219_2215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="dl_applicable",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="super_over_played",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="fake_team",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
