# Generated by Django 3.0.3 on 2020-03-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0063_auto_20200222_0629"),
        ("fixtures", "0062_auto_20200304_1550"),
    ]

    operations = []
