# Generated by Django 3.0.3 on 2020-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0064_merge_20200304_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="calling_code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
