# Generated by Django 3.0.3 on 2020-08-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0065_auto_20200305_1107"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match", unique_together={("tournament", "id", "name")},
        ),
    ]
