# Generated by Django 3.0.3 on 2020-08-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0066_auto_20200826_0424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="fixtures.Tournament",
            ),
        ),
    ]
