# Generated by Django 3.0.3 on 2021-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0068_auto_20210406_0625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playertournamenthistory",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Withdrawn"), (3, "Not playing Matches")],
                default=1,
            ),
        ),
    ]
