# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rules",
            "0004_groupplayerscoringmethod_groupplayerscoringresult_grouppostmatchpredictionscoringmethod_grouppostmat",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
        migrations.AddField(
            model_name="playerscoringmethod",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="enable_for_matches",
            field=models.CharField(default="[ALL]", max_length=50),
        ),
    ]
