# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0005_auto_20170326_0054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="playerscoringmethod",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="predictionscoringmethod",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="predictionsubmissionvalidationrule",
            name="enable_for_matches",
            field=models.CharField(
                default="[ALL]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
    ]
