# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0008_auto_20170326_0216"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="playerscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="predictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[(True, "Apply these changes to ALL clones of this rule.")],
                default=False,
            ),
        ),
    ]
