# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0009_auto_20170327_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="playerscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="predictionscoringmethod",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="predictionsubmissionvalidationrule",
            name="apply_to_clones",
            field=models.BooleanField(
                choices=[
                    (False, "----"),
                    (True, "Apply these changes to ALL clones of this rule."),
                ],
                default=False,
            ),
        ),
    ]
