# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0011_auto_20170327_1314"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupplayerscoringmethod",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
        migrations.RenameField(
            model_name="grouppostmatchpredictionscoringmethod",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
        migrations.RenameField(
            model_name="grouppredictionscoringmethod",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
        migrations.RenameField(
            model_name="grouppredictionsubmissionvalidationrule",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
        migrations.RenameField(
            model_name="playerscoringmethod",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
        migrations.RenameField(
            model_name="postmatchpredictionscoringmethod",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
        migrations.RenameField(
            model_name="predictionscoringmethod",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
        migrations.RenameField(
            model_name="predictionsubmissionvalidationrule",
            old_name="apply_to_cloned_rules",
            new_name="apply_changes_to_cloned_rules",
        ),
    ]
