# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:16
from __future__ import unicode_literals

from django.db import migrations
import python_field.python_field
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0012_auto_20170327_1317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="playerscoringmethod",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethod",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="predictionscoringmethod",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
        migrations.AlterField(
            model_name="predictionsubmissionvalidationrule",
            name="enable_for_matches",
            field=python_field.python_field.PythonCodeField(
                default="lambda match: True",
                help_text="e.g. lambda match: match.match_number in [1,2,3]",
                max_length=50,
                validators=[rules.models.is_code_and_lambda],
            ),
        ),
    ]
