# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:24
from __future__ import unicode_literals

from django.db import migrations
import python_field.python_field


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0013_auto_20170328_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
        migrations.AlterField(
            model_name="playerscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
        migrations.AlterField(
            model_name="predictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
        migrations.AlterField(
            model_name="predictionsubmissionvalidationrule",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default=" _performance * rule.points_or_factor", max_length=750
            ),
        ),
    ]
