# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:39
from __future__ import unicode_literals

from django.db import migrations
import python_field.python_field


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0015_auto_20170328_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="playerscoringmethod",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethod",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="predictionscoringmethod",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="functions",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
    ]
