# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0016_auto_20170329_0539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupplayerscoringresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethodresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="grouppredictionvalidationresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="playerscoringresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethodresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="predictionscoringresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="predictionvalidationresult",
            name="input_values",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
