# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0017_auto_20170402_0131"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="apply_on_batting_performance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="apply_on_bowling_performance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="apply_on_fielding_performance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="apply_on_match_performance",
            field=models.BooleanField(default=False),
        ),
    ]
