# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 10:51
from __future__ import unicode_literals

from django.db import migrations
import python_field.python_field


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0018_auto_20170402_1418"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="playerscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="playerscoringmethod",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethod",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="predictionscoringmethod",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="predictionscoringmethod",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="predictionsubmissionvalidationrule",
            name="calculation",
            field=python_field.python_field.PythonCodeField(
                default="rule.points_or_factor if XXX_performance else 0",
                max_length=750,
            ),
        ),
        migrations.AlterField(
            model_name="predictionsubmissionvalidationrule",
            name="variables",
            field=python_field.python_field.PythonCodeField(
                default="rule, XXX_performance",
                help_text="Replace XXX_performance with any combination of:\n                      batting_performance, bowling_performance,\n                      fielding_performance, player_match_stats",
                max_length=100,
            ),
        ),
    ]
