# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0021_auto_20170531_1251"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupPredictionValidationResult",
            new_name="GroupPredictionSubmissionValidationResult",
        ),
    ]
