# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0022_auto_20180209_0538"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupleaderboardscoringmethodresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="groupplayerscoringresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethodresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="grouptournamentscoringmethodresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="leaderboardscoringmethodresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="playerscoringresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethodresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="predictionscoringresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="predictionvalidationresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tournamentscoringmethodresult",
            name="error_message",
            field=models.TextField(null=True),
        ),
    ]
