# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0023_auto_20180209_0544"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupleaderboardscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouptournamentscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaderboardscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournamentscoringmethod",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupleaderboardscoringmethodresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="groupplayerscoringresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethodresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="grouptournamentscoringmethodresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="leaderboardscoringmethodresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="playerscoringresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethodresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="predictionscoringresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="predictionvalidationresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="tournamentscoringmethodresult",
            name="error_message",
            field=models.TextField(editable=False, null=True),
        ),
    ]
