# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:54
from __future__ import unicode_literals

from django.db import migrations
import python_field.python_field


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0024_auto_20180209_0550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupleaderboardscoringmethod", name="error_message",
        ),
        migrations.RemoveField(
            model_name="groupplayerscoringmethod", name="error_message",
        ),
        migrations.RemoveField(
            model_name="grouppostmatchpredictionscoringmethod", name="error_message",
        ),
        migrations.RemoveField(
            model_name="grouppredictionscoringmethod", name="error_message",
        ),
        migrations.RemoveField(
            model_name="grouppredictionsubmissionvalidationrule", name="error_message",
        ),
        migrations.RemoveField(
            model_name="grouptournamentscoringmethod", name="error_message",
        ),
        migrations.RemoveField(
            model_name="leaderboardscoringmethod", name="error_message",
        ),
        migrations.RemoveField(model_name="playerscoringmethod", name="error_message",),
        migrations.RemoveField(
            model_name="postmatchpredictionscoringmethod", name="error_message",
        ),
        migrations.RemoveField(
            model_name="predictionscoringmethod", name="error_message",
        ),
        migrations.RemoveField(
            model_name="predictionsubmissionvalidationrule", name="error_message",
        ),
        migrations.RemoveField(
            model_name="tournamentscoringmethod", name="error_message",
        ),
        migrations.AddField(
            model_name="groupleaderboardscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="grouptournamentscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="leaderboardscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="playerscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="predictionscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="tournamentscoringmethod",
            name="error_message_function",
            field=python_field.python_field.PythonCodeField(
                blank=True, max_length=1000, null=True
            ),
        ),
    ]
