# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0025_auto_20180209_0554"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupleaderboardscoringmethod", name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="groupplayerscoringmethod", name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="grouppredictionscoringmethod", name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="grouptournamentscoringmethod", name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="leaderboardscoringmethod", name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="playerscoringmethod", name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="postmatchpredictionscoringmethod",
            name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="predictionscoringmethod", name="error_message_function",
        ),
        migrations.RemoveField(
            model_name="tournamentscoringmethod", name="error_message_function",
        ),
    ]
