# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0026_auto_20180209_0606"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionsubmissionvalidationrule",
            name="error_message_function",
        ),
    ]
