# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rules",
            "0027_remove_predictionsubmissionvalidationrule_error_message_function",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="apply_to_submission_type",
            field=models.IntegerField(
                choices=[(1, "Match"), (2, "Tournament")], default=1
            ),
            preserve_default=False,
        ),
    ]
