# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-03 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rules",
            "0028_grouppredictionsubmissionvalidationrule_apply_to_submission_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="apply_to_submission_type",
            field=models.IntegerField(
                choices=[(1, "Match"), (2, "Tournament")], default=1
            ),
            preserve_default=False,
        ),
    ]
