# Generated by Django 2.0.2 on 2018-03-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0029_predictionsubmissionvalidationrule_apply_to_submission_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupleaderboardscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="grouptournamentscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="leaderboardscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="playerscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="predictionscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tournamentscoringmethod",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
