# Generated by Django 2.0.2 on 2019-07-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0033_auto_20190719_0043"),
    ]

    operations = [
        migrations.CreateModel(
            name="R1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_description", models.CharField(max_length=200)),
                ("points", models.IntegerField()),
            ],
            options={"verbose_name_plural": "Rule Ranges", "abstract": False,},
        ),
        migrations.AddField(
            model_name="groupleaderboardscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupplayerscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grouppredictionscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grouptournamentscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboardscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postmatchpredictionscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="predictionscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="predictionsubmissionvalidationrule",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournamentscoringmethod",
            name="display_points_as",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="r1",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rules.PlayerScoringMethod",
            ),
        ),
    ]
