# Generated by Django 2.0.2 on 2019-07-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0034_auto_20190720_0107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupleaderboardscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="groupplayerscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="grouppostmatchpredictionscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="grouppredictionsubmissionvalidationrule",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="grouptournamentscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="leaderboardscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="playerscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="postmatchpredictionscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="predictionscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="predictionsubmissionvalidationrule",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="tournamentscoringmethod",
            name="apply_to_match_type",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test Match")], default=2
            ),
        ),
    ]
