# Generated by Django 3.0.3 on 2020-10-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0035_auto_20190720_0312"),
    ]

    operations = [
        migrations.CreateModel(
            name="R2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_description", models.CharField(max_length=200)),
                ("points", models.IntegerField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rules.PredictionScoringMethod",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Rule Ranges", "abstract": False,},
        ),
    ]
