from django.conf.urls import url, include

from .views import (
    GroupLeaderBoardsView,
    MemberPredictionsView,
    MemberTournamentPredictionsView,
    GroupsView,
    RegisterMemberView,
    RegisterMemberGroupView,
    AllowedMatchSubmissionsView,
    GroupMatchSubmissionsView,
    GroupTournamentSubmissionsView,
    SubmitMatchPredictionView,
    SubmitTournamentPredictionView,
    LastMemberGroupMatchSubmissionView,
    LastMemberGroupTournamentSubmissionView,
    GroupPastMatchesView,
    GroupAllowedMatchesView,
    AllowedTournamentSubmissionsView,
    MemberPointsView,
    CompareTotalPoints,
    GroupsTournamentsView,
    InviteMembersView,
    JoinMemberGroupView,
    TournamentTeamView,
    TeamPlayersView,
    MyTournamentsView,
    PlayerScoringRulesView,
    UpdatePasswordView,
    ResetPasswordView,
    UpcomingMatchesView,
    PredictionScoringRulesView,
    match_prediction_notes_text,
    TouramentScheduleView,
    PredictionScoreView,
    TopScoringPlayersView,
    TopScoringPlayersInTournamentView,
    SingleGroupLeaderBoard,
    TouramentPredictionScoresView,
    ContactFormView,
    MessageBlocksView,
    LoginView,
    AppMediaView,
    MemberVerify,
    MemberVerifyResendMail,
    GroupRewardsView,
    SubmitTournamentRewardView,
    AllowedTournamentSubmissionsDetailsView,
    MatchPredictionFieldStats,
    TournamentPredictionFieldStats,
    MatchPredictionFieldStatsDetails,
    TournamentPredictionFieldStatsDetails,
    RemoveMembershipFromGroupView,
    GroupDetailsView,
    MemberProfile,
    MemberAvatar,
    AllowedTournamentSubmissionsDetailsView,
    MatchStatusView,
)


urlpatterns = [
    url(r"^groups/", GroupsView.as_view()),
    url(r"^group-details/", GroupDetailsView.as_view()),
    url(r"^group-past-matches/", GroupPastMatchesView().as_view()),
    url(r"^group-allowed-matches/", GroupAllowedMatchesView.as_view()),
    url(r"^leader-boards/", GroupLeaderBoardsView.as_view()),
    url(r"^predictions/", MemberPredictionsView.as_view()),
    url(r"^tournament-predictions/", MemberTournamentPredictionsView.as_view()),
    url(r"^api-auth/", include("rest_framework.urls")),
    url(r"^login/", LoginView.as_view()),
    url(r"^register-member/", RegisterMemberView.as_view()),
    url(r"^allowed-match-data/", AllowedMatchSubmissionsView.as_view()),
    url(
        r"^allowed-tournament-submissions/", AllowedTournamentSubmissionsView.as_view()
    ),
    url(
        r"^tournament-submission-data/",
        AllowedTournamentSubmissionsDetailsView.as_view(),
    ),
    url(r"^submit-match-prediction/", SubmitMatchPredictionView.as_view()),
    url(r"^submit-tournament-prediction/", SubmitTournamentPredictionView.as_view()),
    url(r"^running-match-submissions/", GroupMatchSubmissionsView.as_view()),
    url(r"^running-tournament-submissions/", GroupTournamentSubmissionsView.as_view()),
    url(r"^last-match-submission/", LastMemberGroupMatchSubmissionView.as_view()),
    url(
        r"^last-tournament-submission/",
        LastMemberGroupTournamentSubmissionView.as_view(),
    ),
    url(r"^member-points/", MemberPointsView.as_view()),
    url(r"^compare-performance/", CompareTotalPoints.as_view()),
    url(r"^groups-tournaments/", GroupsTournamentsView.as_view()),
    url(r"^tournament-teams/", TournamentTeamView.as_view()),
    url(r"^team-players/", TeamPlayersView.as_view()),
    url(r"^register-member-group/", RegisterMemberGroupView.as_view()),
    url(r"^invite-members/", InviteMembersView.as_view()),
    url(r"^join-member-group/", JoinMemberGroupView.as_view()),
    url(r"^my-tournaments/", MyTournamentsView.as_view()),
    url(r"^player-scoring-rules/", PlayerScoringRulesView.as_view()),
    url(r"^prediction-scoring-rules/", PredictionScoringRulesView.as_view()),
    url(r"^change-password/", UpdatePasswordView.as_view()),
    url(r"^reset-password/", ResetPasswordView.as_view()),
    url(r"^upcoming-matches/", UpcomingMatchesView.as_view()),
    url(r"^match-prediction-notes-text/", match_prediction_notes_text),
    url(r"^tournament-schedule/", TouramentScheduleView.as_view()),
    url(r"^prediction-score/", PredictionScoreView.as_view()),
    url(r"^top-match-performers/", TopScoringPlayersView.as_view()),
    url(r"^top-tournament-performers/", TopScoringPlayersInTournamentView.as_view()),
    url(r"^group-leaderboard/", SingleGroupLeaderBoard.as_view()),
    url(r"^tournament-scores/", TouramentPredictionScoresView.as_view()),
    url(r"^contact-us/", ContactFormView.as_view()),
    url(r"^dynamic-contents/", MessageBlocksView.as_view()),
    url(r"^media/", AppMediaView.as_view()),
    url(r"^group-rewards/", GroupRewardsView.as_view()),
    url(r"^submit-tournament-reward/", SubmitTournamentRewardView.as_view()),
    url(r"^resend-member-verify-mail/", MemberVerifyResendMail.as_view()),
    url(r"^remove-group-membership/", RemoveMembershipFromGroupView.as_view()),
    url(r"^member-profile/", MemberProfile.as_view()),
    url(r"^member-avatar/", MemberAvatar.as_view()),
    url(r"^p-a-m/", MatchPredictionFieldStats.as_view()),
    url(r"^p-a-t/", TournamentPredictionFieldStats.as_view()),
    url(r"^p-a-m-member/", MatchPredictionFieldStatsDetails.as_view()),
    url(r"^p-a-t-member/", TournamentPredictionFieldStatsDetails.as_view()),
    url(
        r"^member-verify/(?P<type>[\w\.-]+)/(?P<token>[\w\.-]+)/",
        MemberVerify.as_view(),
    ),
    url(r"^captcha/", include("captcha.urls")),
    url(f"^match-status/", MatchStatusView.as_view()),
]
