# Generated by Django 2.0.2 on 2018-03-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("configurations", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="configitem",
            name="value",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
