# Generated by Django 2.0.2 on 2018-03-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0032_auto_20180311_0517"),
        ("configurations", "0002_auto_20180310_2345"),
    ]

    operations = [
        migrations.AddField(
            model_name="configitem",
            name="member_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.MemberGroup",
            ),
        )
    ]
