# Generated by Django 2.0.2 on 2018-04-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("configurations", "0003_configitem_member_group")]

    operations = [
        migrations.AlterField(
            model_name="configitem",
            name="value",
            field=models.TextField(blank=True, null=True),
        )
    ]
