# Generated by Django 2.0.2 on 2019-06-10 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0040_auto_20190520_1141"),
        ("configurations", "0004_auto_20180405_0926"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchSubmissionNotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("matches", models.ManyToManyField(to="fixtures.Match")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        )
    ]
