# Generated by Django 2.0.2 on 2019-06-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0040_auto_20190520_1141"),
        ("configurations", "0005_matchsubmissionnotes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configitem", options={"verbose_name_plural": "Config Items"}
        ),
        migrations.AlterModelOptions(
            name="matchsubmissionnotes",
            options={"verbose_name_plural": "Match Submission Notes"},
        ),
        migrations.AlterUniqueTogether(
            name="configitem", unique_together={("name", "tournament")}
        ),
        migrations.AlterUniqueTogether(
            name="matchsubmissionnotes", unique_together={("name", "tournament")}
        ),
    ]
