# Generated by Django 2.0.2 on 2019-06-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("configurations", "0006_auto_20190610_0026")]

    operations = [
        migrations.AddField(
            model_name="matchsubmissionnotes",
            name="value",
            field=models.TextField(blank=True, null=True),
        )
    ]
