# Generated by Django 2.0.2 on 2019-06-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("configurations", "0007_matchsubmissionnotes_value")]

    operations = [
        migrations.AlterField(
            model_name="matchsubmissionnotes",
            name="value",
            field=models.TextField(default=""),
            preserve_default=False,
        )
    ]
