# Generated by Django 2.0.2 on 2019-12-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0057_auto_20191209_0803"),
        ("members", "0053_auto_20190927_0154"),
        ("configurations", "0009_auto_20191209_0701"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "member_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.MemberGroup",
                    ),
                ),
                ("tournaments", models.ManyToManyField(to="fixtures.Tournament")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="feature", unique_together={("name", "member_group")}
        ),
    ]
