# Generated by Django 2.0.2 on 2019-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("configurations", "0010_auto_20191209_1045")]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.IntegerField(choices=[(0, "GROUP_REWARDS")]),
        )
    ]
