# Generated by Django 2.0.2 on 2019-12-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0053_auto_20190927_0154"),
        ("configurations", "0012_auto_20191209_1051"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature", old_name="name", new_name="feature_type",
        ),
        migrations.AlterField(
            model_name="feature",
            name="member_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="features",
                to="members.MemberGroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feature", unique_together={("feature_type", "member_group")},
        ),
    ]
