# Generated by Django 2.0.2 on 2019-12-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0013_auto_20191211_1120"),
    ]

    operations = [
        migrations.RemoveField(model_name="feature", name="tournaments",),
        migrations.AddField(
            model_name="feature",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
