# Generated by Django 2.0.2 on 2019-12-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0057_auto_20191209_0803"),
        ("configurations", "0014_auto_20191211_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="tournaments",
            field=models.ManyToManyField(blank=True, to="fixtures.Tournament"),
        ),
    ]
