# Generated by Django 3.0.3 on 2020-09-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0017_auto_20200913_0221"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature", old_name="data", new_name="data_fn",
        ),
    ]
