# Generated by Django 3.0.3 on 2020-09-13 02:26

from django.db import migrations
import python_field.python_field
import python_field.utils


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0018_auto_20200913_0225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="data_fn",
            field=python_field.python_field.PythonCodeField(
                default="lambda s: {'individual_contribution_amount': 0}",
                max_length=200,
                validators=[python_field.utils.is_code_and_lambda],
            ),
        ),
    ]
