# Generated by Django 3.0.3 on 2020-09-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0019_auto_20200913_0226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="tournament_format",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")],
                null=True,
            ),
        ),
    ]
