# Generated by Django 3.0.3 on 2020-09-13 02:32

from django.db import migrations, models
import fixtures.models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0020_auto_20200913_0227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="tournament_format",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")],
                default=fixtures.models.TournamentFormats["T_TWENTY"],
            ),
        ),
    ]
