# Generated by Django 3.0.3 on 2020-09-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0021_auto_20200913_0232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="feature_type",
            field=models.IntegerField(choices=[(0, "Group Rewards")], default=0),
        ),
    ]
