# Generated by Django 3.0.3 on 2020-09-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("configurations", "0022_auto_20200913_0233"),
    ]

    operations = [
        migrations.RemoveField(model_name="feature", name="tournaments",),
        migrations.AddField(
            model_name="feature",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Tournament",
            ),
        ),
    ]
