# Generated by Django 3.0.3 on 2020-07-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FetchSeries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execute", models.BooleanField(blank=True, default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("job_ref", models.CharField(blank=True, max_length=200)),
                ("series_key", models.CharField(max_length=20)),
            ],
            options={"abstract": False,},
        ),
    ]
