# Generated by Django 3.0.3 on 2020-07-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fetchseries", options={"verbose_name_plural": "Fetch Series"},
        ),
    ]
