# Generated by Django 3.0.3 on 2020-07-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0002_auto_20200726_0211"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fetchseries",
            options={
                "verbose_name": "Fetch Series",
                "verbose_name_plural": "Fetch Series",
            },
        ),
        migrations.RemoveField(model_name="fetchseries", name="job_ref",),
        migrations.AddField(
            model_name="fetchseries",
            name="job_refs",
            field=models.TextField(blank=True),
        ),
    ]
