# Generated by Django 3.0.3 on 2020-08-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0003_auto_20200726_0234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fetchseries",
            name="series_key",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
