# Generated by Django 3.0.3 on 2020-08-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0004_auto_20200802_0150"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fetchseries",
            options={
                "verbose_name": "Fetch Series Job",
                "verbose_name_plural": "Fetch Series Jobs",
            },
        ),
        migrations.AddField(
            model_name="fetchseries",
            name="add_to_all_groups",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fetchseries",
            name="adjust_match_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fetchseries",
            name="adjust_tournament_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fetchseries",
            name="pull_data",
            field=models.BooleanField(default=False),
        ),
    ]
