# Generated by Django 3.0.3 on 2020-08-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0065_auto_20200305_1107"),
        ("auto_jobs", "0005_auto_20200802_0200"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreMatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execute", models.BooleanField(blank=True, default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("job_refs", models.TextField(blank=True)),
                ("fetch_scores", models.BooleanField(default=False)),
                ("convert_predictions", models.BooleanField(default=False)),
                ("score_players", models.BooleanField(default=False)),
                ("leaderboards", models.BooleanField(default=False)),
                ("rewards", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fixtures.Match"
                    ),
                ),
            ],
            options={
                "verbose_name": "Score Match Job",
                "verbose_name_plural": "Score Match Jobs",
            },
        ),
    ]
