# Generated by Django 3.0.3 on 2020-08-02 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0065_auto_20200305_1107"),
        ("auto_jobs", "0006_scorematch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorematch",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fixtures.Match",
                unique=True,
            ),
        ),
    ]
