# Generated by Django 3.0.3 on 2020-08-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0008_auto_20200802_0249"),
    ]

    operations = [
        migrations.RemoveField(model_name="fetchseries", name="adjust_match_data",),
    ]
