# Generated by Django 3.0.3 on 2020-11-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("auto_jobs", "0009_remove_fetchseries_adjust_match_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreSeries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execute", models.BooleanField(blank=True, default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("job_refs", models.TextField(blank=True)),
                ("convert_predictions", models.BooleanField(default=False)),
                ("leaderboards", models.BooleanField(default=False)),
                (
                    "series",
                    models.IntegerField(
                        choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")]
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
