# Generated by Django 3.0.3 on 2020-11-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("auto_jobs", "0010_scoreseries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scoreseries",
            options={
                "verbose_name": "Score Series Job",
                "verbose_name_plural": "Score Series Jobs",
            },
        ),
        migrations.AlterUniqueTogether(
            name="scoreseries", unique_together={("tournament", "series")},
        ),
    ]
