# Generated by Django 3.0.3 on 2020-11-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("auto_jobs", "0011_auto_20201110_0557"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreseries",
            name="runner_up",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runner_up",
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="top_team_four",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_team_four",
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="top_team_one",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_team_one",
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="top_team_three",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_team_three",
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="top_team_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_team_two",
                to="fixtures.Team",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="winner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournament_winner",
                to="fixtures.Team",
            ),
            preserve_default=False,
        ),
    ]
