# Generated by Django 3.0.3 on 2020-11-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0012_auto_20201110_0644"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scoreseries", old_name="top_team_four", new_name="team_four",
        ),
        migrations.RenameField(
            model_name="scoreseries", old_name="top_team_one", new_name="team_one",
        ),
        migrations.RenameField(
            model_name="scoreseries", old_name="top_team_three", new_name="team_three",
        ),
        migrations.RenameField(
            model_name="scoreseries", old_name="top_team_two", new_name="team_two",
        ),
        migrations.RemoveField(model_name="scoreseries", name="runner_up",),
        migrations.RemoveField(model_name="scoreseries", name="winner",),
    ]
