# Generated by Django 3.0.3 on 2020-11-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("auto_jobs", "0013_auto_20201110_0817"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreseries",
            name="batsman_five",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_batsman_five",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="batsman_four",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_batsman_four",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="batsman_one",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_batsman_one",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="batsman_three",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_batsman_three",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="batsman_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_batsman_two",
                to="fixtures.Player",
            ),
        ),
    ]
