# Generated by Django 3.0.3 on 2020-11-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("auto_jobs", "0014_auto_20201110_0902"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreseries",
            name="bowler_five",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_bowler_five",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="bowler_four",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_bowler_four",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="bowler_one",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_bowler_one",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="bowler_three",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_bowler_three",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="bowler_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_bowler_two",
                to="fixtures.Player",
            ),
        ),
    ]
