# Generated by Django 3.0.3 on 2020-11-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("auto_jobs", "0015_auto_20201110_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreseries",
            name="mvp_one",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mvp_one",
                to="fixtures.Player",
            ),
        ),
        migrations.AddField(
            model_name="scoreseries",
            name="mvp_two",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mvp_two",
                to="fixtures.Player",
            ),
        ),
    ]
