# Generated by Django 3.0.3 on 2020-11-11 05:11

from django.db import migrations
import python_field.python_field
import python_field.utils


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0017_auto_20201110_2235"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreseries",
            name="bonus_configuration",
            field=python_field.python_field.PythonCodeField(
                default="{}", max_length=200, validators=[python_field.utils.is_dict]
            ),
        ),
    ]
