# Generated by Django 3.0.3 on 2020-11-11 05:21

from django.db import migrations
import python_field.python_field
import python_field.utils


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0019_auto_20201111_0517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreseries",
            name="bonus_configuration",
            field=python_field.python_field.PythonCodeField(
                default="# Config Syntax\n    # [\n    #  {\n    #     'mg': Member Group ID,\n    #     'members': (Member IDs,)\n    #     'bonus': NNNN\n    #  },\n    #\n    # ....\n    # ]\n",
                max_length=200,
                validators=[python_field.utils.is_dict],
            ),
        ),
    ]
