# Generated by Django 3.0.3 on 2020-12-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0024_auto_20201111_0628"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreseries",
            name="win_series_margin",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True
            ),
        ),
    ]
