# Generated by Django 3.0.3 on 2020-12-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0067_auto_20200826_0924"),
        ("auto_jobs", "0025_scoreseries_win_series_margin"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreseries",
            name="player_of_the_tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player_of_the_tournament",
                to="fixtures.Player",
            ),
        ),
    ]
