# Generated by Django 3.0.3 on 2021-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_jobs", "0027_auto_20210410_0432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreseries",
            name="win_series_margin",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                ],
                null=True,
            ),
        ),
    ]
