# Generated by Django 3.0.3 on 2021-11-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_jobs', '0029_scorematch_revert_prediction_conversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreseries',
            name='score_t20_wc',
            field=models.BooleanField(default=False),
        ),
    ]
