# Generated by Django 3.0.3 on 2022-05-31 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0069_auto_20210406_0626'),
        ('auto_jobs', '0030_scoreseries_score_t20_wc'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreseries',
            name='last_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_team', to='fixtures.Team'),
        ),
    ]
