# Generated by Django 2.0.2 on 2019-08-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0051_membership_active"),
        ("fixtures", "0048_auto_20190819_0903"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_name", models.CharField(max_length=100)),
                ("content_block", models.TextField()),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Member"
                    ),
                ),
                (
                    "member_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.MemberGroup",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
            options={"ordering": ["message_name"],},
        ),
    ]
