# Generated by Django 2.0.2 on 2019-08-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DynamicContent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamiccontent",
            name="member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.Member",
            ),
        ),
        migrations.AlterField(
            model_name="dynamiccontent",
            name="member_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.MemberGroup",
            ),
        ),
        migrations.AlterField(
            model_name="dynamiccontent",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fixtures.Tournament",
            ),
        ),
    ]
