# Generated by Django 2.0.2 on 2019-08-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DynamicContent", "0002_auto_20190826_1851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamiccontent",
            name="notes",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
