# Generated by Django 2.0.2 on 2019-09-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0049_auto_20190911_0939"),
        ("members", "0051_membership_active"),
        ("DynamicContent", "0003_auto_20190826_1904"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_name", models.CharField(max_length=100, unique=True)),
                ("content_block", models.TextField()),
                ("notes", models.TextField(blank=True, max_length=2000, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Member",
                    ),
                ),
                (
                    "member_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.MemberGroup",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="dynamiccontent", name="member",),
        migrations.RemoveField(model_name="dynamiccontent", name="member_group",),
        migrations.RemoveField(model_name="dynamiccontent", name="tournament",),
        migrations.DeleteModel(name="DynamicContent",),
    ]
