# Generated by Django 2.0.2 on 2019-10-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fixtures", "0052_auto_20190921_0121"),
        ("members", "0053_auto_20190927_0154"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentReward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_reward_amount", models.IntegerField(default=0)),
                ("is_financial", models.BooleanField(default=True)),
                ("activated", models.BooleanField(default=False)),
                ("agreement_text", models.TextField(null=True)),
                (
                    "member_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.MemberGroup",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentRewardParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contributor", models.BooleanField(default=True)),
                ("has_paid", models.BooleanField(default=False)),
                ("notes", models.TextField(null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Member"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.MemberGroup",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixtures.Tournament",
                    ),
                ),
            ],
        ),
    ]
