# Generated by Django 2.0.2 on 2019-10-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rewards", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="tournamentrewardparticipant",
            old_name="has_paid",
            new_name="contribution_received",
        ),
        migrations.AddField(
            model_name="tournamentrewardparticipant",
            name="contribution_amount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournamentreward",
            name="agreement_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
