# Generated by Django 2.0.2 on 2019-10-14 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("rewards", "0002_auto_20191013_0453")]

    operations = [
        migrations.RemoveField(
            model_name="tournamentrewardparticipant", name="participant"
        ),
        migrations.AddField(
            model_name="tournamentreward",
            name="chosen_reward_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tournamentrewardparticipant",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="fixtures.Tournament",
            ),
        ),
    ]
