# Generated by Django 2.0.2 on 2019-10-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("rewards", "0003_auto_20191014_0254")]

    operations = [
        migrations.AlterField(
            model_name="tournamentrewardparticipant",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="rewards.TournamentReward",
            ),
        )
    ]
