# Generated by Django 2.0.2 on 2019-10-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rewards", "0004_auto_20191014_0305")]

    operations = [
        migrations.RenameField(
            model_name="tournamentreward",
            old_name="chosen_reward_amount",
            new_name="reward_pool",
        ),
        migrations.AlterField(
            model_name="tournamentrewardparticipant",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
