# Generated by Django 2.0.2 on 2019-10-29 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0053_auto_20190927_0154"),
        ("rewards", "0005_auto_20191017_1646"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentRewardAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_agreed", models.DateTimeField(auto_now_add=True)),
                ("agreement_text", models.TextField(editable=False)),
                (
                    "admin_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Member"
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="tournamentreward",
            old_name="suggested_reward_amount",
            new_name="suggested_reward_pool",
        ),
        migrations.AddField(
            model_name="tournamentreward",
            name="tournament_format",
            field=models.IntegerField(
                choices=[(1, "One Day"), (2, "T-20"), (3, "Test match")], default=2
            ),
        ),
        migrations.AddField(
            model_name="tournamentrewardagreement",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreement_records",
                to="rewards.TournamentReward",
            ),
        ),
    ]
