# Generated by Django 2.0.2 on 2019-10-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0052_auto_20190921_0121"),
        ("members", "0053_auto_20190927_0154"),
        ("rewards", "0006_auto_20191029_0054"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tournamentreward",
            unique_together={("tournament", "tournament_format", "member_group")},
        )
    ]
