# Generated by Django 2.0.2 on 2019-10-29 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("rewards", "0007_auto_20191029_0119")]

    operations = [
        migrations.AddField(
            model_name="tournamentreward",
            name="changes_allowed_up_to",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
