# Generated by Django 2.0.2 on 2019-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0008_tournamentreward_changes_allowed_up_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentreward",
            name="rewards_calculations_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournamentrewardagreement",
            name="rewards_calculations_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
