# Generated by Django 2.0.2 on 2020-01-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0009_auto_20191211_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentreward",
            name="contribution_per_member",
            field=models.IntegerField(default=0),
        ),
    ]
