# Generated by Django 2.0.2 on 2019-10-10 10:48

import app_media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("fixtures", "0052_auto_20190921_0121")]

    operations = [
        migrations.CreateModel(
            name="AppMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_name",
                    models.CharField(default="ec8419fa55", max_length=10, unique=True),
                ),
                (
                    "media_size",
                    models.IntegerField(
                        choices=[(1, "icon"), (2, "small"), (3, "medium"), (4, "large")]
                    ),
                ),
                (
                    "media_type",
                    models.IntegerField(choices=[(1, "image"), (2, "video")]),
                ),
                (
                    "media_file",
                    models.FileField(
                        upload_to=app_media.models.PathAndRename(
                            random_name="ec8419fa55", sub_path="app-media/"
                        )
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="fixtures.Country",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="fixtures.Player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="fixtures.Team",
                    ),
                ),
            ],
        )
    ]
