# Generated by Django 2.0.2 on 2019-10-11 10:53

import app_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app_media", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="appmedia",
            name="media_file",
            field=models.FileField(
                upload_to=app_media.models.PathAndRename(
                    random_name="4879515ce9", sub_path="app-media/"
                )
            ),
        ),
        migrations.AlterField(
            model_name="appmedia",
            name="media_name",
            field=models.CharField(default="4879515ce9", max_length=10, unique=True),
        ),
    ]
