# Generated by Django 2.0.2 on 2019-10-11 14:26

import app_media.models
from django.db import migrations, models
import python_field.python_field
import python_field.utils


class Migration(migrations.Migration):

    dependencies = [("app_media", "0002_auto_20191011_1623")]

    operations = [
        migrations.AddField(
            model_name="appmedia",
            name="media_note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="appmedia",
            name="media_spec",
            field=python_field.python_field.PythonCodeField(
                default="lambda : True",
                max_length=200,
                validators=[python_field.utils.is_code_and_lambda],
            ),
        ),
        migrations.AddField(
            model_name="appmedia",
            name="original_filename",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="appmedia",
            name="media_file",
            field=models.FileField(
                upload_to=app_media.models.PathAndRename(sub_path="app-media/")
            ),
        ),
        migrations.AlterField(
            model_name="appmedia",
            name="media_name",
            field=models.CharField(
                default=app_media.models.generate_file_name, max_length=10, unique=True
            ),
        ),
    ]
