# Generated by Django 2.0.2 on 2019-10-12 01:39

import app_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0003_auto_20191011_1956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmedia",
            name="media_file",
            field=models.FileField(upload_to=app_media.models.PathAndRename()),
        ),
    ]
