# Generated by Django 2.0.2 on 2019-10-29 12:01

import app_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0004_auto_20191012_0139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmedia",
            name="media_file",
            field=models.FileField(upload_to=app_media.models.set_path_and_file_name),
        ),
    ]
