# Generated by Django 2.0.2 on 2019-11-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0004_auto_20191012_0139"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmedia",
            name="media_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="appmedia",
            name="media_type",
            field=models.IntegerField(
                choices=[(1, "image"), (2, "video"), (3, "banner")]
            ),
        ),
    ]
