# Generated by Django 2.0.2 on 2019-12-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0053_auto_20190927_0154"),
        ("app_media", "0005_auto_20191029_1731"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmedia",
            name="member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="members.Member",
            ),
        ),
    ]
