# Generated by Django 2.0.2 on 2019-11-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0005_auto_20191108_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmedia",
            name="media_size",
            field=models.IntegerField(
                choices=[
                    (1, "icon"),
                    (2, "small"),
                    (3, "medium"),
                    (4, "large"),
                    (5, "banner"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="appmedia",
            name="media_type",
            field=models.IntegerField(choices=[(1, "image"), (2, "video")]),
        ),
    ]
