# Generated by Django 2.0.2 on 2019-12-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0052_auto_20190921_0121"),
        ("app_media", "0006_appmedia_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmedia",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="fixtures.Tournament",
            ),
        ),
    ]
