# Generated by Django 2.0.2 on 2019-11-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0006_auto_20191108_1501"),
    ]

    operations = [
        migrations.RemoveField(model_name="appmedia", name="media_title",),
    ]
