# Generated by Django 2.0.2 on 2019-12-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0007_appmedia_tournament"),
        ("app_media", "0007_remove_appmedia_media_title"),
    ]

    operations = []
