# Generated by Django 2.0.2 on 2019-12-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0008_merge_20191212_0715"),
        ("app_media", "0008_merge_20191211_1556"),
    ]

    operations = []
