# Generated by Django 2.0.2 on 2020-02-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0009_merge_20191227_1943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmedia",
            name="member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="members.Member",
            ),
        ),
    ]
