# Generated by Django 2.0.2 on 2019-11-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True, null=True)),
                (
                    "username",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("path", models.CharField(max_length=255, null=True)),
                ("accessed_on", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
